### ISSUE TITLE
Psychic emanator upgrade applied accross all save files

### ISSUE THREAD

**Issue by ItsNickBarry** [Mehni/MoreFactionInteraction#35]
When the psychic emanator is upgraded after a science expo event, the increased power usage and range is applied to all save files.  This lasts until the game is restarted.

Also, the description of the event is unclear.  What does "at the cost of ... longevity" mean?  The device will break down more often?

**Comment by Mehni** [comment]
That bug was fixed in fa33f6ee some months ago. The description is flavour text, I don't think I increased the rate of breakdown for it.

fa33f6ee

**Comment by ItsNickBarry** [comment]
Any idea why the bug persists in my installation?  I installed it via Steam about a month ago.

**Comment by Mehni** [comment]
I'll have a look.  This sounds like a bug that is similar, but not the same.
